### ISSUE TITLE
Is this alive?

### ISSUE THREAD

**Issue by ariloudev** [Landoop/Landoop-On-Cloudera#1]
Is the project even alive?

**Comment by Antwnis** [comment]
Hi @ariloudev 

The project has evolved quite a lot  
Have a look at https://www.landoop.com/devops/kafka-on-cloudera/

We are also bringing **Lenses for Apache Kafka** onto Cloudera distribution
https://www.landoop.com/kafka-lenses/

**Comment by ariloudev** [comment]
@Antwnis yeah so you no longer have a free version for it?

**Comment by Antwnis** [comment]
This is now a cost-effective commercial offering

**Comment by ariloudev** [comment]
@Antwnis Got it :-) Good luck!
